# Generated by Django 4.2.23 on 2025-07-21 04:08

import audio_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Paciente 001 - Consulta inicial - Dr. González', max_length=200, verbose_name='Identificación del Caso')),
                ('archivo_audio', models.FileField(help_text='Formatos soportados: MP3, WAV, OGG, M4A, AAC', upload_to=audio_app.models.audio_upload_path, verbose_name='Archivo de Audio')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre Original')),
                ('formato_audio', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('ogg', 'OGG'), ('m4a', 'M4A'), ('aac', 'AAC')], max_length=10, verbose_name='Formato')),
                ('duracion_segundos', models.IntegerField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('tamaño_archivo', models.BigIntegerField(verbose_name='Tamaño (bytes)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado del Procesamiento')),
                ('transcripcion', models.TextField(blank=True, null=True, verbose_name='Transcripción del Audio')),
                ('analisis_ia', models.TextField(blank=True, null=True, verbose_name='Análisis de IA')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('doctor', models.CharField(blank=True, max_length=100, verbose_name='Doctor Responsable')),
                ('paciente_id', models.CharField(blank=True, max_length=50, verbose_name='ID del Paciente')),
                ('tipo_consulta', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Consulta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Audio Médico',
                'verbose_name_plural': 'Audios Médicos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
